require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-sequel

AllCops:
  NewCops: enable

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false