require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-sequel

AllCops:
  NewCops: enable
  Exclude:
    - 'fhir/citation.rb' # FHIR model conventions trigger many cops
    - 'test/db/schema.rb' # Rails generated code from cedar_admin triggers many cops

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false
  
Metrics/MethodLength:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 10
