require:
  - rubocop-rake
  - rubocop-minitest
  - rubocop-sequel

AllCops:
  NewCops: enable
  Exclude:
    - 'fhir/citation.rb' # FHIR model conventions trigger many cops
    - 'test/db/schema.rb' # Rails generated code from cedar_admin triggers many cops

Style/GuardClause:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 8

Metrics/PerceivedComplexity:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Minitest/MultipleAssertions:
  Max: 10
