image: ruby:2.7.1
pipelines:
  default:
    - parallel:
      - step:
          name: Test
          caches:
            - bundler
          services:
            - postgres
          script:
            - cp test/db/config.ci.yml test/db/config.yml
            - bundle install
            - bundle exec rake test
      - step:
          name: Rubocop
          caches:
            - bundler
          script:
            - bundle install
            - bundle exec rake rubocop
      - step:
          name: Lint code
          script:
            - ruby -wc **/*.rb

definitions:
  caches:
    bundler: ./vendor
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'cedar_api_test'
        POSTGRES_USER: 'postgres'
        POSTGRES_PASSWORD: 'postgres'
