image: ruby:2.7.1
pipelines:
  default:
    - parallel:
      - step:
          name: Test
          script:
            - bundle install
            - bundle exec rake test
      - step:
          name: Rubocop
          script:
            - bundle install
            - bundle exec rake rubocop
      - step:
          name: Lint code
          script:
            - ruby -wc **/*.rb
