# Sequel gem database configuration

production:
  database_url: <%= ENV["DATABASE_URL"] %>

development:
  database_url: "postgres://localhost/cedar_admin_development"

test:
  database_url: "postgres://localhost/cedar_api_test"
