# Sequel gem database configuration

production:
  database_url: <%= ENV["DATABASE_URL"] %>

development:
  host: localhost
  adapter: postgres
  encoding: unicode
  database: cedar_admin_development

test:
  host: localhost
  adapter: postgres
  encoding: unicode
  database: cedar_api_test
