# Sequel gem database configuration

production:
  host: db
  adapter: postgres
  encoding: unicode
  database: cedar_admin_production
  username: cedar_admin
  password: <%= ENV['CEDAR_ADMIN_DATABASE_PASSWORD'] %>

development:
  host: localhost
  adapter: postgres
  encoding: unicode
  database: cedar_admin_development

test:
  host: localhost
  adapter: postgres
  encoding: unicode
  database: cedar_api_test
